"""receipt departments and spending only

Receipt lines can be a shop department ("COMESTIBELS") or count as spending only;
departments learned per store; when a receipt was booked. Also forgets receipt
aliases whose text is plainly a department, so they stop auto-linking.

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-02 12:32:11.301415
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('text_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'store_id', 'text_key')
    )
    with op.batch_alter_table('receipt_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('spending_only', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('spending_category', sa.String(length=80), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
    # "COMESTIBELS" -> whatever was linked the first time: that memory is wrong by nature
    from app.services.departments import is_department_text
    conn = op.get_bind()
    aliases = sa.table('receipt_aliases', sa.column('id', sa.String), sa.column('text_key', sa.String))
    stale = [i for i, key in conn.execute(sa.select(aliases.c.id, aliases.c.text_key)) if is_department_text(key)]
    if stale:
        conn.execute(aliases.delete().where(aliases.c.id.in_(stale)))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    with op.batch_alter_table('receipt_lines', schema=None) as batch_op:
        batch_op.drop_column('spending_category')
        batch_op.drop_column('spending_only')
        batch_op.drop_column('department')

    op.drop_table('receipt_departments')
    # ### end Alembic commands ###
