"""store profiles

Stores get an address, phone and tax number (CRIB) read from receipts, and a map location
(lat/lon; geocoded from the address, or placed by hand).

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-02 13:06:56.352993
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('crib', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('location_source', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('location_source')
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')
        batch_op.drop_column('crib')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
