"""geocode cache

What OpenStreetMap Nominatim answered per search (found or not), so each store address is
looked up once.

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 13:26:50.509792
"""
from alembic import op
import sqlalchemy as sa


revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('query', sa.String(length=400), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.Column('label', sa.String(length=400), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('query')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
