"""fun stats

Stores get a kind (minimarket / supermarket / other; null = guess from the name), receipts
the time printed on them, households a home point on the map.

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-02 13:34:03.724343
"""
from alembic import op
import sqlalchemy as sa


revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_lat', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('home_lon', sa.Double(), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_time', sa.Time(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('purchased_time')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('home_lon')
        batch_op.drop_column('home_lat')

    # ### end Alembic commands ###
